project:
  type: book

book:
  title: "packagesBook"
  author: "Alex Boyle"
  date: "7/30/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - git.qmd
    - addCode.qmd
    - use_r.qmd
    - loadall.qmd
    - check.qmd
    - description.qmd
    - documentation.qmd
    - install.qmd
    - test.qmd
    - stringr.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

